import { StyleSheet, Dimensions } from 'react-native';
import { colors, spacing, typography } from '../../theme';

const { width } = Dimensions.get('window');
const scale = size => Math.round((width / 390) * size);

export const styles = StyleSheet.create({
  pageBackground: {
    backgroundColor: '#f8f5ff',
    flex: 1,
  },
  listContent: {
    paddingBottom: 100, // Space for BottomDock
  },
  heroHeader: {
    paddingTop: scale(52),
    paddingHorizontal: scale(24),
    paddingBottom: scale(80),
    position: 'relative',
    overflow: 'hidden',
  },
  heroDecorCircle1: {
    position: 'absolute',
    top: -40,
    right: -40,
    width: 160,
    height: 160,
    borderRadius: 80,
    backgroundColor: 'rgba(255,255,255,0.1)',
  },
  heroDecorCircle2: {
    position: 'absolute',
    top: 20,
    right: 20,
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: 'rgba(255,255,255,0.08)',
  },
  heroDecorCircle3: {
    position: 'absolute',
    bottom: -20,
    left: -20,
    width: 120,
    height: 120,
    borderRadius: 60,
    backgroundColor: 'rgba(255,255,255,0.07)',
  },
  heroTopRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    zIndex: 1,
  },
  greetingPill: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.18)',
    borderRadius: 20,
    paddingVertical: 4,
    paddingHorizontal: 12,
    marginBottom: 12,
    alignSelf: 'flex-start',
  },
  greetingDot: {
    width: 7,
    height: 7,
    borderRadius: 3.5,
    backgroundColor: '#86efac',
    marginRight: 6,
  },
  greetingText: {
    fontSize: scale(12),
    color: '#fff',
    fontWeight: '500',
  },
  brandTitle: {
    fontSize: scale(36),
    fontWeight: '900',
    color: '#fff',
    lineHeight: scale(40),
    letterSpacing: -0.5,
  },
  brandSub: {
    fontSize: scale(12),
    color: 'rgba(255,255,255,0.65)',
    marginTop: 4,
    letterSpacing: 1,
    textTransform: 'uppercase',
  },
  bellBtn: {
    width: 46,
    height: 46,
    borderRadius: 16,
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.3)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  notifDot: {
    position: 'absolute',
    top: 10,
    right: 12,
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#f43f5e',
    borderWidth: 2,
    borderColor: 'rgba(108,99,255,0.6)',
    zIndex: 1,
  },
  searchBar: {
    marginTop: 20,
    backgroundColor: 'rgba(255,255,255,0.2)',
    borderRadius: 14,
    paddingVertical: 12,
    paddingHorizontal: 16,
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.25)',
  },
  searchText: {
    fontSize: scale(16),
    color: 'rgba(255,255,255,0.6)',
    marginLeft: 10,
  },
  recordCardContainer: {
    paddingHorizontal: 20,
    marginTop: -44,
    zIndex: 10,
  },
  recordBtn: {
    width: '100%',
    borderRadius: 22,
    paddingVertical: 20,
    paddingHorizontal: 22,
    backgroundColor: '#fff',
    flexDirection: 'row',
    alignItems: 'center',
    shadowColor: '#6c63ff',
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.15,
    shadowRadius: 40,
    elevation: 8,
  },
  recordIconBg: {
    width: 52,
    height: 52,
    borderRadius: 26,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#6c63ff',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.4,
    shadowRadius: 20,
    elevation: 5,
  },
  recordTextCol: {
    flex: 1,
    marginLeft: 14,
  },
  recordTitle: {
    fontSize: scale(19),
    fontWeight: '700',
    color: '#0f1628',
    letterSpacing: -0.2,
  },
  recordSubtitle: {
    fontSize: scale(14),
    color: '#9ca3af',
    marginTop: 3,
  },
  recordChevronBg: {
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: '#f0edff',
    alignItems: 'center',
    justifyContent: 'center',
  },
  sectionContainer: {
    paddingTop: 28,
    paddingHorizontal: 20,
  },
  sectionHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 14,
  },
  sectionTitle: {
    fontSize: scale(17),
    fontWeight: '700',
    color: '#0f1628',
    letterSpacing: -0.2,
  },
  sectionSubtitle: {
    fontSize: scale(12),
    color: '#9ca3af',
    marginTop: 2,
  },
  weekBtn: {
    backgroundColor: '#ede9ff',
    borderRadius: 10,
    paddingVertical: 5,
    paddingHorizontal: 12,
  },
  weekBtnText: {
    color: '#6c63ff',
    fontSize: scale(12),
    fontWeight: '600',
  },
  statGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
  },
  statTile: {
    width: '48%',
    backgroundColor: '#fff',
    borderRadius: 20,
    paddingTop: 18,
    paddingBottom: 16,
    paddingHorizontal: 16,
    marginBottom: 14,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 16,
    elevation: 2,
  },
  statTileHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 10,
  },
  statChip: {
    width: 34,
    height: 34,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  statChipInner: {
    width: 10,
    height: 10,
    borderRadius: 5,
  },
  miniBarChart: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    height: 24,
    gap: 2,
  },
  miniBar: {
    width: 4,
    borderRadius: 2,
  },
  statValue: {
    fontSize: scale(30),
    fontWeight: '700',
    color: '#0f1628',
    lineHeight: scale(34),
  },
  statLabel: {
    fontSize: scale(16),
    fontWeight: '600',
    color: '#0f1628',
    marginTop: 4,
  },
  statSubLabel: {
    fontSize: scale(13),
    color: '#6b7280',
    marginTop: 2,
  },
  quickActionsContainer: {
    paddingTop: 24,
    paddingHorizontal: 20,
  },
  quickActionsTitle: {
    fontSize: scale(17),
    fontWeight: '700',
    color: '#0f1628',
    letterSpacing: -0.2,
    marginBottom: 14,
  },
  quickGrid: {
    flexDirection: 'row',
    justifyContent: 'flex-start',
    gap: 16,
  },
  quickActionBtn: {
    backgroundColor: '#fff',
    borderRadius: 16,
    paddingTop: 16,
    paddingBottom: 12,
    paddingHorizontal: 4,
    alignItems: 'center',
    width: '23%',
  },
  quickActionIconText: {
    fontSize: scale(22),
    marginBottom: 8,
  },
  quickActionLabel: {
    fontSize: scale(13),
    fontWeight: '600',
  },
  recentReportsContainer: {
    paddingTop: 28,
    paddingHorizontal: 20,
  },
  viewAllBtnText: {
    color: '#6c63ff',
    fontSize: scale(15),
    fontWeight: '600',
  },
  tabsRow: {
    flexDirection: 'row',
    gap: 8,
    marginBottom: 16,
  },
  tabBtn: {
    backgroundColor: '#fff',
    borderRadius: 20,
    paddingVertical: 6,
    paddingHorizontal: 16,
  },
  tabBtnActive: {
    backgroundColor: '#6c63ff',
    shadowColor: '#6c63ff',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.35,
    shadowRadius: 14,
    elevation: 4,
  },
  tabBtnText: {
    fontSize: scale(14),
    fontWeight: '600',
    color: '#9ca3af',
    textTransform: 'capitalize',
  },
  tabBtnTextActive: {
    color: '#fff',
  },
  reportRow: {
    backgroundColor: '#fff',
    borderRadius: 18,
    paddingVertical: 16,
    paddingHorizontal: 18,
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 14,
    elevation: 2,
  },
  reportIconBox: {
    width: 44,
    height: 44,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 14,
  },
  reportIconText: {
    fontSize: scale(20),
  },
  reportInfo: {
    flex: 1,
  },
  reportName: {
    fontSize: scale(16),
    fontWeight: '700',
    color: '#0f1628',
  },
  reportMeta: {
    fontSize: scale(14),
    color: '#9ca3af',
    marginTop: 2,
  },
  reportStatusBox: {
    alignItems: 'flex-end',
  },
  reportStatusBadge: {
    borderRadius: 20,
    paddingVertical: 3,
    paddingHorizontal: 10,
    marginBottom: 4,
  },
  reportStatusText: {
    fontSize: scale(13),
    fontWeight: '600',
  },
  reportTime: {
    fontSize: scale(13),
    color: '#b0b8cc',
  },
  emptyCard: {
    backgroundColor: '#fff',
    borderRadius: 18,
    paddingVertical: 36,
    paddingHorizontal: 24,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 14,
    elevation: 2,
  },
  emptyEmoji: {
    fontSize: scale(32),
    marginBottom: 10,
  },
  emptyTitle: {
    fontSize: scale(18),
    fontWeight: '600',
    color: '#0f1628',
  },
  emptyBody: {
    fontSize: scale(12),
    color: '#9ca3af',
    marginTop: 4,
  },
  tipCard: {
    marginTop: 24,
    marginHorizontal: 20,
    borderRadius: 22,
    paddingVertical: 22,
    paddingHorizontal: 22,
    flexDirection: 'row',
    alignItems: 'center',
    shadowColor: '#10b981',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.28,
    shadowRadius: 28,
    elevation: 6,
    position: 'relative',
    overflow: 'hidden',
  },
  tipDecor: {
    position: 'absolute',
    top: -20,
    right: -20,
    width: 100,
    height: 100,
    borderRadius: 50,
    backgroundColor: 'rgba(255,255,255,0.1)',
  },
  tipIconBox: {
    width: 48,
    height: 48,
    borderRadius: 16,
    backgroundColor: 'rgba(255,255,255,0.2)',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 16,
  },
  tipIcon: {
    fontSize: scale(24),
  },
  tipInfo: {
    flex: 1,
  },
  tipTitle: {
    fontSize: scale(13),
    fontWeight: '700',
    color: '#fff',
  },
  tipDesc: {
    fontSize: scale(12),
    color: 'rgba(255,255,255,0.75)',
    marginTop: 3,
    lineHeight: scale(18),
  },
  pressed: {
    opacity: 0.75,
  }
});

export default styles;
