import {StyleSheet} from 'react-native';
import { colors, spacing, typography } from '../../theme';

export const createStyles = scale =>
  StyleSheet.create({
  pageBackground: {
    backgroundColor: '#f8f5ff',
    flex: 1,
  },
  heroHeader: {
    paddingTop: scale(52),
    paddingHorizontal: scale(24),
    paddingBottom: scale(40),
    position: 'relative',
    overflow: 'hidden',
  },
  heroDecorCircle1: {
    position: 'absolute',
    top: -40,
    right: -40,
    width: 160,
    height: 160,
    borderRadius: 80,
    backgroundColor: 'rgba(255,255,255,0.1)',
  },
  heroDecorCircle2: {
    position: 'absolute',
    top: 20,
    right: 20,
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: 'rgba(255,255,255,0.08)',
  },
  heroDecorCircle3: {
    position: 'absolute',
    bottom: -20,
    left: -20,
    width: 120,
    height: 120,
    borderRadius: 60,
    backgroundColor: 'rgba(255,255,255,0.07)',
  },
  heroTopRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    zIndex: 1,
  },
  heroTitleColumn: {
    flex: 1,
    paddingRight: scale(12),
  },
  brandBadge: {
    width: scale(46),
    height: scale(46),
    borderRadius: scale(16),
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.3)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  brandTitle: {
    fontSize: scale(36),
    fontWeight: '900',
    color: '#fff',
    lineHeight: scale(40),
    letterSpacing: -0.5,
  },
  brandSub: {
    fontSize: scale(14),
    color: 'rgba(255,255,255,0.75)',
    marginTop: 4,
  },
  searchBar: {
    marginTop: 20,
    backgroundColor: 'rgba(255,255,255,0.2)',
    borderRadius: 14,
    paddingVertical: 12,
    paddingHorizontal: 16,
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.25)',
  },
  searchText: {
    fontSize: scale(16),
    color: '#fff',
    marginLeft: 10,
    flex: 1,
    padding: 0,
  },
  contentContainer: {
    paddingHorizontal: 20,
    paddingTop: 16,
  },
  heading: {
    ...typography.largeHeading,
    fontSize: 30,
    marginTop: spacing.sm,
  },
  subheading: {
    ...typography.body,
    color: colors.textMuted,
    fontSize: 14,
    marginBottom: spacing.md,
  },
  search: {
    ...typography.body,
    backgroundColor: colors.surface,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: colors.border,
    paddingVertical: spacing.md,
    paddingHorizontal: spacing.lg,
    color: colors.textPrimary,
    marginBottom: spacing.md,
  },
  countLine: {
    fontSize: 13,
    fontWeight: '600',
    color: colors.textMuted,
    marginBottom: spacing.sm,
  },
  patientRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.md,
    backgroundColor: colors.primaryBackground,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: colors.border,
    shadowColor: colors.primaryAccent,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.05,
    shadowRadius: 16,
    elevation: 3,
    padding: spacing.md,
    paddingRight: 12,
    marginBottom: spacing.md,
  },
  pressed: {
    opacity: 0.75,
  },
  avatar: {
    width: 48,
    height: 48,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarText: {
    fontSize: 15,
    fontWeight: '700',
    letterSpacing: 0.5,
  },
  body: {
    flex: 1,
  },
  name: {
    fontSize: 16,
    fontWeight: '700',
    color: colors.textPrimary,
  },
  meta: {
    fontSize: 13,
    color: colors.textSecondary,
    marginTop: 2,
  },
  countPill: {
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.primaryAccent,
    backgroundColor: colors.primaryLight,
  },
  countPillText: {
    fontSize: 11,
    fontWeight: '800',
    color: colors.primaryAccent,
  },
  emptyBox: {
    alignItems: 'center',
    paddingVertical: spacing.xl,
    paddingHorizontal: spacing.lg,
  },
  emptyTitle: {
    ...typography.body,
    fontSize: 17,
    fontWeight: '700',
    color: colors.textPrimary,
  },
  emptyBody: {
    ...typography.body,
    fontSize: 14,
    color: colors.textMuted,
    textAlign: 'center',
    marginTop: spacing.xs,
  },
});

export default createStyles;
