import {Platform, StyleSheet} from 'react-native';
import { colors, spacing } from '../../theme';

export const createStyles = scale =>
  StyleSheet.create({
  container: {
    backgroundColor: '#FAF8FF',
    flex: 1,
    position: 'relative',
  },
  // Background Blobs
  blobContainer: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: 0,
    overflow: 'hidden',
  },
  blob1: {
    position: 'absolute',
    top: -100,
    left: -80,
    width: 380,
    height: 380,
    borderRadius: 190,
    backgroundColor: 'rgba(129, 140, 248, 0.15)',
  },
  blob2: {
    position: 'absolute',
    top: 120,
    right: -100,
    width: 300,
    height: 300,
    borderRadius: 150,
    backgroundColor: 'rgba(244, 114, 182, 0.15)',
  },
  blob3: {
    position: 'absolute',
    top: 320,
    left: -60,
    width: 260,
    height: 260,
    borderRadius: 130,
    backgroundColor: 'rgba(52, 211, 153, 0.1)',
  },
  
  // Content container
  scrollContent: {
    paddingHorizontal: 20,
    paddingTop: Platform.OS === 'ios' ? 50 : 30,
    paddingBottom: 40,
    zIndex: 10,
  },
  flexOne: {
    flex: 1,
  },

  // Header
  headerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 24,
  },
  glassBtn: {
    width: 40,
    height: 40,
    borderRadius: 13,
    backgroundColor: 'rgba(255,255,255,0.75)',
    borderWidth: 1.5,
    borderColor: 'rgba(109,79,255,0.15)',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#6D4FFF',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 10,
    elevation: 2,
  },
  headerTitle: {
    fontSize: scale(12),
    fontWeight: '700',
    color: '#7C5CFC',
    letterSpacing: 1.2,
    textTransform: 'uppercase',
  },

  // Hero Band
  heroBand: {
    borderRadius: 24,
    paddingTop: 24,
    paddingHorizontal: 22,
    paddingBottom: 22,
    marginBottom: 18,
    position: 'relative',
    overflow: 'hidden',
    shadowColor: '#6D4FFF',
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.35,
    shadowRadius: 40,
    elevation: 8,
  },
  heroBlob1: {
    position: 'absolute',
    top: -30,
    right: -30,
    width: 130,
    height: 130,
    borderRadius: 65,
    backgroundColor: 'rgba(255,255,255,0.08)',
  },
  heroBlob2: {
    position: 'absolute',
    bottom: -20,
    right: 40,
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: 'rgba(255,255,255,0.06)',
  },
  liveSessionBadge: {
    backgroundColor: 'rgba(255,255,255,0.2)',
    borderRadius: 8,
    paddingVertical: 4,
    paddingHorizontal: 10,
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'flex-start',
    marginBottom: 12,
  },
  liveDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: '#4ADE80',
    marginRight: 6,
    shadowColor: '#4ADE80',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.8,
    shadowRadius: 6,
    elevation: 2,
  },
  liveText: {
    fontSize: scale(10),
    fontWeight: '700',
    color: '#fff',
    letterSpacing: 0.6,
    textTransform: 'uppercase',
  },
  heroTitle: {
    fontSize: scale(28),
    fontWeight: '800',
    color: '#fff',
    lineHeight: scale(32),
    letterSpacing: -0.5,
    marginBottom: 8,
  },
  heroTitleLight: {
    fontWeight: '400',
    fontStyle: 'italic',
    opacity: 0.85,
  },
  heroDesc: {
    fontSize: scale(13),
    color: 'rgba(255,255,255,0.75)',
    lineHeight: scale(20),
  },

  // Stat Cards
  statCardsGrid: {
    flexDirection: 'row',
    gap: 10,
    marginBottom: 16,
  },
  statCard: {
    flex: 1,
    borderRadius: 20,
    paddingVertical: 16,
    paddingHorizontal: 14,
    position: 'relative',
    overflow: 'hidden',
    elevation: 6,
  },
  statCardBlob1: {
    position: 'absolute',
    top: -24,
    right: -24,
    width: 90,
    height: 90,
    borderRadius: 45,
    backgroundColor: 'rgba(255,255,255,0.1)',
  },
  statCardBlob2: {
    position: 'absolute',
    bottom: -16,
    right: 14,
    width: 55,
    height: 55,
    borderRadius: 27.5,
    backgroundColor: 'rgba(255,255,255,0.07)',
  },
  statCardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 10,
  },
  statCardIconBox: {
    width: 32,
    height: 32,
    borderRadius: 9,
    backgroundColor: 'rgba(255,255,255,0.22)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  statCardBadge: {
    backgroundColor: 'rgba(255,255,255,0.2)',
    borderRadius: 99,
    paddingVertical: 3,
    paddingHorizontal: 7,
  },
  statCardBadgeText: {
    fontSize: scale(9),
    fontWeight: '700',
    color: '#fff',
    letterSpacing: 0.6,
    textTransform: 'uppercase',
  },
  statCardLabel: {
    fontSize: scale(14),
    color: '#FFFFFF',
    letterSpacing: 0.6,
    textTransform: 'uppercase',
    fontWeight: '800',
    marginBottom: 3,
  },
  statCardValue: {
    fontSize: scale(20),
    fontWeight: '600',
    color: '#fff',
    letterSpacing: -0.2,
    marginBottom: 3,
  },
  statCardSub: {
    fontSize: scale(12),
    color: 'rgba(255,255,255,0.5)',
  },

  // Mini Stats Row
  // Tab Switcher
  tabSwitcher: {
    flexDirection: 'row',
    borderRadius: 20,
    padding: 5,
    marginBottom: 16,
    backgroundColor: 'rgba(255,255,255,0.7)',
    borderWidth: 1.5,
    borderColor: 'rgba(109,79,255,0.15)',
    shadowColor: '#6D4FFF',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 20,
    elevation: 3,
    gap: 5,
  },
  tabBtn: {
    flex: 1,
    paddingVertical: 12,
    paddingHorizontal: 10,
    borderRadius: 15,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 7,
  },
  tabBtnIconBox: {
    width: 24,
    alignItems: 'center',
    justifyContent: 'center',
  },
  tabBtnTextCol: {
    flex: 1,
  },
  tabBtnLabel: {
    fontSize: scale(16),
    fontWeight: '700',
    lineHeight: scale(16),
  },
  tabBtnSub: {
    fontSize: scale(12),
    marginTop: 3,
  },

  // Transcript Panel
  transcriptPanel: {
    borderRadius: 22,
    overflow: 'hidden',
    marginBottom: 16,
    backgroundColor: 'rgba(255,255,255,0.85)',
    borderWidth: 1.5,
    borderColor: 'rgba(109,79,255,0.12)',
    shadowColor: '#6D4FFF',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.1,
    shadowRadius: 32,
    elevation: 4,
  },
  panelTopStripe: {
    height: 4,
  },
  panelHeader: {
    paddingVertical: 14,
    paddingHorizontal: 16,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(109,79,255,0.08)',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  panelHeaderLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  panelHeaderIconBg: {
    width: 36,
    height: 36,
    borderRadius: 11,
    alignItems: 'center',
    justifyContent: 'center',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.35,
    shadowRadius: 12,
    elevation: 4,
  },
  panelHeaderTitle: {
    fontSize: scale(16),
    fontWeight: '700',
    color: '#1A1035',
  },
  panelHeaderSub: {
    fontSize: scale(12),
    color: '#9E9BB5',
    marginTop: 2,
  },
  useBadge: {
    paddingVertical: 5,
    paddingHorizontal: 11,
    borderRadius: 99,
    borderWidth: 1,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 2,
  },
  useBadgeText: {
    fontSize: scale(10),
    fontWeight: '700',
    letterSpacing: 0.4,
    textTransform: 'uppercase',
  },
  panelEditor: {
    width: '100%',
    minHeight: 180,
    padding: 16,
    fontSize: scale(14),
    lineHeight: scale(22),
    color: '#1A1035',
    textAlignVertical: 'top',
  },
  panelFooter: {
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderTopWidth: 1,
    borderTopColor: 'rgba(109,79,255,0.08)',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  wordCountRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
  },
  wordCountText: {
    fontSize: scale(14),
    fontWeight: '600',
    color: '#9E9BB5',
  },
  copyBtn: {
    width: 32,
    height: 32,
    borderRadius: 9,
    alignItems: 'center',
    justifyContent: 'center',
  },

  // Action Buttons
  actionsContainer: {
    flexDirection: 'column',
    gap: 10,
    paddingBottom: 24,
  },
  addMoreBtn: {
    width: '100%',
    paddingVertical: 15,
    paddingHorizontal: 20,
    borderRadius: 18,
    backgroundColor: 'rgba(255,255,255,0.85)',
    borderWidth: 2,
    borderStyle: 'dashed',
    borderColor: 'rgba(109,79,255,0.3)',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    shadowColor: '#6D4FFF',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 16,
    elevation: 2,
  },
  addMoreIconBg: {
    width: 24,
    height: 24,
    borderRadius: 6,
    alignItems: 'center',
    justifyContent: 'center',
  },
  addMoreText: {
    fontSize: scale(15),
    fontWeight: '700',
    color: '#6D4FFF',
  },
  generateBtn: {
    width: '100%',
    paddingVertical: 17,
    paddingHorizontal: 20,
    borderRadius: 18,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    shadowColor: '#6D4FFF',
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.42,
    shadowRadius: 36,
    elevation: 8,
    position: 'relative',
    overflow: 'hidden',
  },
  generateBtnShimmer: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    height: '50%',
    backgroundColor: 'rgba(255,255,255,0.12)',
    borderTopLeftRadius: 18,
    borderTopRightRadius: 18,
  },
  generateText: {
    fontSize: scale(15),
    fontWeight: '800',
    color: '#fff',
    letterSpacing: -0.1,
  },
  generateArrowBox: {
    marginLeft: 'auto',
    width: 28,
    height: 28,
    borderRadius: 8,
    backgroundColor: 'rgba(255,255,255,0.2)',
    alignItems: 'center',
    justifyContent: 'center',
  },

  // Notices
  fallbackNotice: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    backgroundColor: colors.primaryLight,
    borderRadius: 10,
    borderLeftWidth: 3,
    borderLeftColor: colors.secondaryAccent,
    paddingVertical: spacing.sm,
    paddingHorizontal: spacing.md,
    marginTop: spacing.sm,
    marginBottom: 16,
  },
  fallbackText: {
    flex: 1,
    fontSize: scale(13),
    lineHeight: scale(19),
    color: colors.textPrimary,
  },
  fallbackDismiss: {
    fontSize: scale(14),
    fontWeight: '700',
    color: colors.textMuted,
    paddingHorizontal: spacing.xs,
  },
  statusRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 16,
  },
  statusText: {
    fontSize: scale(12),
    fontWeight: '700',
    color: '#94A3B8',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  retry: {
    fontSize: scale(13),
    fontWeight: '700',
    color: '#2F6BFF',
  },
  pendingBlock: {
    padding: 24,
    minHeight: 180,
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.sm,
  },
  pendingTitle: {
    fontSize: scale(15),
    fontWeight: '700',
    color: colors.textPrimary,
    textAlign: 'center',
  },
  pendingDetail: {
    fontSize: scale(13),
    lineHeight: scale(20),
    color: '#94A3B8',
    textAlign: 'center',
    maxWidth: 260,
  },
  placeholder: {
    padding: 24,
    fontSize: scale(14),
    lineHeight: scale(22),
    color: '#94A3B8',
    minHeight: 180,
  },

  pressed: {
    opacity: 0.7,
  },
  disabled: {
    opacity: 0.5,
  },
});
export default createStyles;
