export const DICTATION_LANGUAGES = [
  {
    code: 'en',
    tag: 'en-IN',
    translationCode: 'en-IN',
    englishName: 'English (India)',
    nativeName: 'English',
    script: 'latin',
    voice: 'en-IN-PrabhatNeural',
    gender: 'Female',
    confirmed: true,
  },
  {
    code: 'as',
    tag: 'as-IN',
    translationCode: 'as-IN',
    englishName: 'Assamese',
    nativeName: 'অসমীয়া',
    script: 'bengali',
    voice: 'as-IN-YashicaNeural',
    gender: 'Female',
    confirmed: true,
  },
  {
    code: 'bn',
    tag: 'bn-IN',
    translationCode: 'bn-IN',
    englishName: 'Bengali',
    nativeName: 'বাংলা',
    script: 'bengali',
    voice: 'bn-IN-TanishaaNeural',
    gender: 'Female',
    confirmed: true,
  },
  {
    code: 'brx',
    tag: 'brx-IN',
    translationCode: 'brx-IN',
    englishName: 'Bodo',
    nativeName: 'बड़ो',
    script: 'devanagari',
    voice: null,
    gender: null,
    confirmed: false,
  },
  {
    code: 'doi',
    tag: 'doi-IN',
    translationCode: 'doi-IN',
    englishName: 'Dogri',
    nativeName: 'डोगरी',
    script: 'devanagari',
    voice: null,
    gender: null,
    confirmed: false,
  },
  {
    code: 'gu',
    tag: 'gu-IN',
    translationCode: 'gu-IN',
    englishName: 'Gujarati',
    nativeName: 'ગુજરાતી',
    script: 'gujarati',
    voice: 'gu-IN-DhwaniNeural',
    gender: 'Female',
    confirmed: true,
  },
  {
    code: 'hi',
    tag: 'hi-IN',
    translationCode: 'hi-IN',
    englishName: 'Hindi',
    nativeName: 'हिन्दी',
    script: 'devanagari',
    voice: 'hi-IN-SwaraNeural',
    gender: 'Female',
    confirmed: true,
  },
  {
    code: 'kn',
    tag: 'kn-IN',
    translationCode: 'kn-IN',
    englishName: 'Kannada',
    nativeName: 'ಕನ್ನಡ',
    script: 'kannada',
    voice: 'kn-IN-SapnaNeural',
    gender: 'Female',
    confirmed: true,
  },
  {
    code: 'ks-deva',
    tag: 'ks-IN',
    translationCode: 'ks-dn-IN',
    englishName: 'Kashmiri (Devanagari)',
    nativeName: 'कॉशुर',
    script: 'devanagari',
    voice: null,
    gender: null,
    confirmed: false,
  },
  {
    code: 'ks-arab',
    tag: 'ks-IN',
    translationCode: 'ks-ar-IN',
    englishName: 'Kashmiri (Perso-Arabic)',
    nativeName: 'کٲشُر',
    script: 'perso-arabic',
    voice: null,
    gender: null,
    confirmed: false,
  },
  {
    code: 'kok',
    tag: 'kok-IN',
    translationCode: 'gom-IN',
    englishName: 'Konkani',
    nativeName: 'कोंकणी',
    script: 'devanagari',
    voice: null,
    gender: null,
    confirmed: false,
  },
  {
    code: 'mai',
    tag: 'mai-IN',
    translationCode: 'mai-IN',
    englishName: 'Maithili',
    nativeName: 'मैथिली',
    script: 'devanagari',
    voice: null,
    gender: null,
    confirmed: false,
  },
  {
    code: 'ml',
    tag: 'ml-IN',
    translationCode: 'ml-IN',
    englishName: 'Malayalam',
    nativeName: 'മലയാളം',
    script: 'malayalam',
    voice: 'ml-IN-SobhanaNeural',
    gender: 'Female',
    confirmed: true,
  },
  {
    code: 'mni',
    tag: 'mni-IN',
    translationCode: 'mni-IN',
    englishName: 'Manipuri',
    nativeName: 'ꯃꯤꯇꯩꯂꯣꯟ',
    script: 'meitei-mayek',
    voice: null,
    gender: null,
    confirmed: false,
  },
  {
    code: 'mr',
    tag: 'mr-IN',
    translationCode: 'mr-IN',
    englishName: 'Marathi',
    nativeName: 'मराठी',
    script: 'devanagari',
    voice: 'mr-IN-AarohiNeural',
    gender: 'Female',
    confirmed: true,
  },
  {
    code: 'ne',
    tag: 'ne-IN',
    translationCode: 'ne-IN',
    englishName: 'Nepali',
    nativeName: 'नेपाली',
    script: 'devanagari',
    voice: 'ne-NP-HemkalaNeural',
    gender: 'Female',
    confirmed: true,
  },
  {
    code: 'or',
    tag: 'or-IN',
    translationCode: 'or-IN',
    englishName: 'Odia',
    nativeName: 'ଓଡ଼ିଆ',
    script: 'odia',
    voice: 'or-IN-SubhasiniNeural',
    gender: 'Female',
    confirmed: true,
  },
  {
    code: 'pa',
    tag: 'pa-IN',
    translationCode: 'pa-IN',
    englishName: 'Punjabi',
    nativeName: 'ਪੰਜਾਬੀ',
    script: 'gurmukhi',
    voice: 'pa-IN-VaaniNeural',
    gender: 'Female',
    confirmed: true,
  },
  {
    code: 'sa',
    tag: 'sa-IN',
    translationCode: 'sa-IN',
    englishName: 'Sanskrit',
    nativeName: 'संस्कृतम्',
    script: 'devanagari',
    voice: null,
    gender: null,
    confirmed: false,
  },
  {
    code: 'sat',
    tag: 'sat-IN',
    translationCode: 'sat-IN',
    englishName: 'Santali',
    nativeName: 'ᱥᱟᱱᱛᱟᱲᱤ',
    script: 'ol-chiki',
    voice: null,
    gender: null,
    confirmed: false,
  },
  {
    code: 'sd',
    tag: 'sd-IN',
    translationCode: 'sd-dn-IN',
    englishName: 'Sindhi (Devanagari)',
    nativeName: 'सिन्धी',
    script: 'devanagari',
    voice: null,
    gender: null,
    confirmed: false,
  },
  {
    code: 'ta',
    tag: 'ta-IN',
    translationCode: 'ta-IN',
    englishName: 'Tamil',
    nativeName: 'தமிழ்',
    script: 'tamil',
    voice: 'ta-IN-PallaviNeural',
    gender: 'Female',
    confirmed: true,
  },
  {
    code: 'te',
    tag: 'te-IN',
    translationCode: 'te-IN',
    englishName: 'Telugu',
    nativeName: 'తెలుగు',
    script: 'telugu',
    voice: 'te-IN-ShrutiNeural',
    gender: 'Female',
    confirmed: true,
  },
  {
    code: 'ur',
    tag: 'ur-IN',
    translationCode: 'ur-IN',
    englishName: 'Urdu',
    nativeName: 'اردو',
    script: 'perso-arabic',
    voice: 'ur-IN-GulNeural',
    gender: 'Female',
    confirmed: true,
  },
];

export const DEFAULT_LANGUAGE_CODE = 'en';
export const LANGUAGE_BY_CODE = Object.fromEntries(
  DICTATION_LANGUAGES.map(language => [language.code, language]),
);

export const LANGUAGE_BY_TAG = DICTATION_LANGUAGES.reduce((map, language) => {
  if (!(language.tag in map)) {
    map[language.tag] = language;
  }
  return map;
}, {});

export const LEGACY_LANGUAGE_ALIAS = {
  ks: 'ks-arab',
};

export const resolveLegacyCode = code => LEGACY_LANGUAGE_ALIAS[code] ?? code;
export const isLatinScript = code =>
  (LANGUAGE_BY_CODE[code] ?? LANGUAGE_BY_CODE[DEFAULT_LANGUAGE_CODE]).script ===
  'latin';

export const isKnownLanguage = code => Boolean(LANGUAGE_BY_CODE[code]);
export const displayFor = code =>
  LANGUAGE_BY_CODE[code] ?? LANGUAGE_BY_CODE[DEFAULT_LANGUAGE_CODE];
export const recognizerTag = code => displayFor(code).tag;
export const translationCodeFor = code =>
  LANGUAGE_BY_CODE[code]?.translationCode ?? '';
