export default {
  code: "as",
  reviewed: false,

  forms: {
    "shortness of breath": ["উশাহ লোৱাত কষ্ট হোৱা"],
    "difficulty in breathing": ["শ্বাস-প্ৰশ্বাসত অসুবিধা"],
    "difficulty breathing": ["শ্বাস-প্ৰশ্বাসত অসুবিধা"],
    "breathing difficulty": ["শ্বাস-প্ৰশ্বাসত অসুবিধা"],
    "loss of appetite": ["ভোক কমি যোৱা"],
    "burning sensation": ["জ্বলন অনুভৱ"],
    "sore throat": ["ডিঙিৰ বিষ"],
    "chest pain": ["বুকুৰ বিষ"],
    "body pain": ["শৰীৰৰ বিষ"],
    "back pain": ["পিঠিৰ বিষ"],
    "joint pain": ["গাঁঠিৰ বিষ"],
    "muscle pain": ["পেশীৰ বিষ"],
    "stomach pain": ["পেটৰ বিষ"],
    "abdominal pain": ["পেটৰ বিষ"],
    "ear pain": ["কাণৰ বিষ"],
    "tooth pain": ["দাঁতৰ বিষ"],
    "throat pain": ["ডিঙিৰ বিষ"],
    "runny nose": ["পানী ওলোৱা নাক"],
    "blocked nose": ["বন্ধ কৰা নাক"],
    "night sweats": ["ৰাতিৰ ঘাম"],
    "blurred vision": ["অস্পষ্ট দৃষ্টিশক্তি"],
    "loose motions": ["আলসুৱা চলাচল"],
    "body ache": ["শৰীৰৰ বিষ"],
    "stomach ache": ["পেটৰ বিষ"],
    "fever": ["জ্বৰ"],
    "cough": ["কাহ"],
    "cold": ["ঠাণ্ডা"],
    "headache": ["মূৰৰ বিষ"],
    "tiredness": ["ভাগৰ লগা"],
    "weakness": ["দুৰ্বলতা"],
    "fatigue": ["ক্লান্তি"],
    "vomiting": ["বমি হোৱা"],
    "nausea": ["বমি হোৱা"],
    "dizziness": ["মূৰ ঘূৰণি"],
    "giddiness": ["মূৰ ঘূৰণি"],
    "sneezing": ["হাঁচি ওলোৱা"],
    "diarrhea": ["ডায়েৰিয়া"],
    "diarrhoea": ["ডায়েৰিয়া"],
    "constipation": ["কোষ্ঠকাঠিন্য"],
    "rash": ["ফোঁহা"],
    "itching": ["খজুৱতি"],
    "chills": ["ঠাণ্ডা"],
    "breathlessness": ["উশাহ বন্ধ হোৱা"],
    "insomnia": ["অনিদ্ৰা"],
    "cramps": ["কঁপনি"],
    "swelling": ["ফুলা"],
    "restlessness": ["অস্থিৰতা"],
    "sweating": ["ঘাম ওলোৱা"],
    "shivering": ["কঁপি থকা"],
  },
};
