export default {
  code: "bn",
  reviewed: false,
  forms: {
    "shortness of breath": ["শ্বাসকষ্ট"],
    "difficulty in breathing": ["শ্বাসকষ্ট"],
    "difficulty breathing": ["শ্বাসকষ্ট"],
    "breathing difficulty": ["শ্বাসকষ্ট"],
    "loss of appetite": ["ক্ষুধা কমে যাওয়া"],
    "burning sensation": ["জ্বলন্ত সংবেদন"],
    "sore throat": ["গলাব্যথা"],
    "chest pain": ["বুকের ব্যথা"],
    "body pain": ["শরীরের ব্যথা"],
    "back pain": ["পিঠের ব্যথা"],
    "joint pain": ["গাঁটের ব্যথা"],
    "muscle pain": ["পেশী ব্যথা"],
    "stomach pain": ["পেটে ব্যথা"],
    "abdominal pain": ["পেটে ব্যথা"],
    "ear pain": ["কানের ব্যথা"],
    "tooth pain": ["দাঁতের ব্যথা"],
    "throat pain": ["গলাব্যথা"],
    "runny nose": ["নাক দিয়ে পানি পড়া"],
    "blocked nose": ["নাক বন্ধ"],
    "night sweats": ["রাতের ঘাম"],
    "blurred vision": ["অস্পষ্ট দৃষ্টি"],
    "loose motions": ["বদহজম"],
    "body ache": ["শরীরের ব্যথা"],
    "stomach ache": ["পেটে ব্যথা"],
    "fever": ["জ্বর"],
    "cough": ["কাশি"],
    "cold": ["ঠাণ্ডা"],
    "headache": ["মাথাব্যথা"],
    "tiredness": ["ক্লান্তি"],
    "weakness": ["দুর্বলতা"],
    "fatigue": ["ক্লান্তি"],
    "vomiting": ["বমি"],
    "nausea": ["বমি ভাব"],
    "dizziness": ["মাথা ঘোরা"],
    "giddiness": ["চঞ্চলতা"],
    "sneezing": ["হাঁচি"],
    "diarrhea": ["ডায়রিয়া"],
    "diarrhoea": ["ডায়রিয়া"],
    "constipation": ["কোষ্ঠকাঠিন্য"],
    "rash": ["ফুসকুড়ি"],
    "itching": ["চুলকানি"],
    "chills": ["ঠাণ্ডা লাগা"],
    "breathlessness": ["শ্বাসকষ্ট"],
    "insomnia": ["অনিদ্রা"],
    "cramps": ["খিঁচুনি"],
    "swelling": ["ফোলাভাব"],
    "restlessness": ["অস্থিরতা"],
    "sweating": ["ঘাম ঝরছে"],
    "shivering": ["কাঁপছে"],
  },
};
