export default {
  code: "hi",
  reviewed: false,

  forms: {
    "shortness of breath": ["सांस की तकलीफ"],
    "difficulty in breathing": ["सांस लेने में तकलीफ"],
    "difficulty breathing": ["साँस लेने में कठिनाई"],
    "breathing difficulty": ["सांस लेने में तकलीफ"],
    "loss of appetite": ["भूख की कमी"],
    "burning sensation": ["जलन महसूस"],
    "sore throat": ["गले में दर्द"],
    "chest pain": ["सीने में दर्द"],
    "body pain": ["शरीर में दर्द"],
    "back pain": ["पीठ दर्द"],
    "joint pain": ["जोड़ों का दर्द"],
    "muscle pain": ["हड्डियों में दर्द"],
    "stomach pain": ["पेट दर्द"],
    "abdominal pain": ["पेट दर्द"],
    "ear pain": ["कान दर्द"],
    "tooth pain": ["दाँतों का दर्द"],
    "throat pain": ["गले में दर्द"],
    "runny nose": ["नाक बहना"],
    "blocked nose": ["अवरुद्ध नाक"],
    "night sweats": ["रात में पसीना आता है"],
    "blurred vision": ["धुंधली दृष्टि"],
    "loose motions": ["दस्त"],
    "body ache": ["शरीर में दर्द"],
    "stomach ache": ["पेट दर्द"],
    "fever": ["बुखार"],
    "cough": ["खाँसी"],
    "cold": ["ठंड"],
    "headache": ["सिरदर्द"],
    "tiredness": ["थकान"],
    "weakness": ["कमजोरी"],
    "fatigue": ["थकान"],
    "vomiting": ["उल्टी"],
    "nausea": ["मतली"],
    "dizziness": ["चक्कर"],
    "giddiness": ["चक्कर"],
    "sneezing": ["छींकना"],
    "diarrhea": ["दस्त"],
    "diarrhoea": ["दस्त"],
    "constipation": ["कब्ज"],
    "rash": ["चकत्ते"],
    "itching": ["खुजली"],
    "chills": ["ठंड लगना"],
    "breathlessness": ["सांस फूलना"],
    "insomnia": ["अनिद्रा"],
    "cramps": ["ऐंठन"],
    "swelling": ["सूजन"],
    "restlessness": ["बेचैनी"],
    "sweating": ["पसीना"],
    "shivering": ["कांप रहा है"],
  },
};
