export default {
  code: "ml",
  reviewed: false,
  forms: {
    "shortness of breath": ["ശ്വാസതടസ്സം"],
    "difficulty in breathing": ["ശ്വസിക്കാൻ ബുദ്ധിമുട്ട്"],
    "difficulty breathing": ["ശ്വസിക്കാൻ ബുദ്ധിമുട്ട്"],
    "breathing difficulty": ["ശ്വാസതടസ്സം"],
    "loss of appetite": ["വിശപ്പ് കുറയുന്നു"],
    "burning sensation": ["കത്തുന്ന വികാരം"],
    "sore throat": ["തൊണ്ടവേദന"],
    "chest pain": ["നെഞ്ച് വേദന"],
    "body pain": ["ശരീര വേദന"],
    "back pain": ["നടുവേദന"],
    "joint pain": ["സന്ധി വേദന"],
    "muscle pain": ["പേശികളുടെ വേദന"],
    "stomach pain": ["വയറുവേദന"],
    "abdominal pain": ["വയറുവേദന"],
    "ear pain": ["ചെവി വേദന"],
    "tooth pain": ["പല്ലുവേദന"],
    "throat pain": ["തൊണ്ടവേദന"],
    "runny nose": ["മൂക്കൊലിപ്പ്"],
    "blocked nose": ["അടഞ്ഞ മൂക്ക്"],
    "night sweats": ["രാത്രി വിയർപ്പ്"],
    "blurred vision": ["മങ്ങിയ കാഴ്ച"],
    "loose motions": ["ചലനങ്ങൾ"],
    "body ache": ["ശരീരവേദന"],
    "stomach ache": ["വയറുവേദന"],
    "fever": ["പനി"],
    "cough": ["ചുമ"],
    "cold": ["തണുപ്പ്"],
    "headache": ["തലവേദന"],
    "tiredness": ["ക്ഷീണം"],
    "weakness": ["ബലഹീനത"],
    "fatigue": ["ക്ഷീണം"],
    "vomiting": ["ഛർദ്ദി"],
    "nausea": ["ഓക്കാനം"],
    "dizziness": ["തലകറക്കം"],
    "giddiness": ["തലകറക്കം"],
    "sneezing": ["തുമ്മൽ"],
    "diarrhea": ["വയറിളക്കം"],
    "diarrhoea": ["വയറിളക്കം"],
    "constipation": ["മലബന്ധം"],
    "rash": ["ചൊറിച്ചിൽ"],
    "itching": ["ചൊറിച്ചിൽ"],
    "chills": ["തണുപ്പ്"],
    "breathlessness": ["ശ്വാസതടസ്സം"],
    "insomnia": ["ഉറക്കമില്ലായ്മ"],
    "cramps": ["മലബന്ധം"],
    "swelling": ["വീക്കം"],
    "restlessness": ["അസ്വസ്ഥത"],
    "sweating": ["വിയർപ്പ്"],
    "shivering": ["വിറയ്ക്കുന്നു"],
  },
};
