export default {
  code: "or",
  reviewed: false,
  forms: {
    "shortness of breath": ["ନିଶ୍ୱାସ ନେବାରେ ଅସୁବିଧା"],
    "difficulty in breathing": ["ନିଶ୍ୱାସ ନେବାରେ ଅସୁବିଧା"],
    "difficulty breathing": ["ନିଶ୍ୱାସ ନେବାରେ ଅସୁବିଧା"],
    "breathing difficulty": ["ନିଶ୍ୱାସ ନେବାରେ ଅସୁବିଧା"],
    "loss of appetite": ["ଭୋକ କମିଯିବା"],
    "burning sensation": ["ଜ୍ୱଳନ୍ତ ଅନୁଭବ"],
    "sore throat": ["ଗଳାରେ ଯନ୍ତ୍ରଣା"],
    "chest pain": ["ଛାତି ଯନ୍ତ୍ରଣା"],
    "body pain": ["ଶରୀର ଯନ୍ତ୍ରଣା"],
    "back pain": ["ପିଠି ଯନ୍ତ୍ରଣା"],
    "joint pain": ["ଗଣ୍ଠି ଯନ୍ତ୍ରଣା"],
    "muscle pain": ["ମାଂସପେଶୀ ଯନ୍ତ୍ରଣା"],
    "stomach pain": ["ପେଟ ଯନ୍ତ୍ରଣା"],
    "abdominal pain": ["ପେଟ ଯନ୍ତ୍ରଣା"],
    "ear pain": ["କାନ ଯନ୍ତ୍ରଣା"],
    "tooth pain": ["ଦାନ୍ତ ଯନ୍ତ୍ରଣା"],
    "throat pain": ["ଗଳାରେ ଯନ୍ତ୍ରଣା"],
    "runny nose": ["ନାକରୁ ପାଣି ବୋହିବା"],
    "blocked nose": ["ନାକ ବନ୍ଦ"],
    "night sweats": ["ରାତିରେ ଝାଳ ବୋହିବା"],
    "blurred vision": ["ଅସ୍ପଷ୍ଟ ଦୃଷ୍ଟି"],
    "loose motions": ["ହାଲୁକା ଗତିବିଧି"],
    "body ache": ["ଶରୀର ଯନ୍ତ୍ରଣା"],
    "stomach ache": ["ପେଟ ଯନ୍ତ୍ରଣା"],
    "fever": ["ଜ୍ୱର"],
    "cough": ["କାଶ"],
    "cold": ["ଥଣ୍ଡା"],
    "headache": ["ମୁଣ୍ଡବିନ୍ଧା"],
    "tiredness": ["ଥକାପଣ"],
    "weakness": ["ଦୁର୍ବଳତା"],
    "fatigue": ["ଥକାପଣ"],
    "vomiting": ["ବାନ୍ତି"],
    "nausea": ["ବାନ୍ତି"],
    "dizziness": ["ମୁଣ୍ଡ ବୁଲାଇବା"],
    "giddiness": ["ଚଞ୍ଚଲତା"],
    "sneezing": ["ଛିଙ୍କିବା"],
    "diarrhea": ["ତରଳ ଝାଡ଼ା"],
    "diarrhoea": ["ତରଳ ଝାଡ଼ା"],
    "constipation": ["କୋଷ୍ଠକାଠିନ୍ୟ"],
    "rash": ["ରାସ୍"],
    "itching": ["ଖଞ୍ଜିବା"],
    "chills": ["ଥଣ୍ଡା"],
    "breathlessness": ["ନିଶ୍ୱାସ ନେବାରେ ଅସୁବିଧା"],
    "insomnia": ["ନିଦ୍ରାହୀନତା"],
    "cramps": ["ଯନ୍ତ୍ରଣା"],
    "swelling": ["ଫୁଲା"],
    "restlessness": ["ଅସ୍ଥିରତା"],
    "sweating": ["ଝାଳ ବୋହିବା"],
    "shivering": ["ଥରି ଉଠୁଛି"],
  },
};
