export default {
  code: "ta",
  reviewed: false,
  forms: {
    "shortness of breath": ["மூச்சுத் திணறல்"],
    "difficulty in breathing": ["மூச்சு விடுவதில் சிரமம்"],
    "difficulty breathing": ["மூச்சு விடுவதில் சிரமம்"],
    "breathing difficulty": ["மூச்சு விடுவதில் சிரமம்"],
    "loss of appetite": ["பசியின்மை இழப்பு"],
    "burning sensation": ["எரியும் உணர்வு"],
    "sore throat": ["தொண்டை புண்"],
    "chest pain": ["நெஞ்சு வலி"],
    "body pain": ["உடல் வலி"],
    "back pain": ["முதுகு வலி"],
    "joint pain": ["மூட்டு வலி"],
    "muscle pain": ["தசை வலி"],
    "stomach pain": ["வயிற்று வலி"],
    "abdominal pain": ["வயிற்று வலி"],
    "ear pain": ["காது வலி"],
    "tooth pain": ["பல் வலி"],
    "throat pain": ["தொண்டை வலி"],
    "runny nose": ["மூக்கு ஒழுகுதல்"],
    "blocked nose": ["மூக்கு அடைப்பு"],
    "night sweats": ["இரவு வியர்வை"],
    "blurred vision": ["மங்கலான பார்வை"],
    "loose motions": ["அஜீரணங்கள்"],
    "body ache": ["உடல் வலி"],
    "stomach ache": ["வயிற்று வலி"],
    "fever": ["காய்ச்சல்"],
    "cough": ["இருமல்"],
    "cold": ["குளிர்"],
    "headache": ["தலைவலி"],
    "tiredness": ["சோர்வு"],
    "weakness": ["பலவீனம்"],
    "fatigue": ["சோர்வு"],
    "vomiting": ["வாந்தியெடுத்தல்"],
    "nausea": ["குமட்டல்"],
    "dizziness": ["மயக்கம்"],
    "giddiness": ["தலைச்சுற்றல்"],
    "sneezing": ["தும்மல்"],
    "diarrhea": ["வயிற்றுப்போக்கு"],
    "diarrhoea": ["வயிற்றுப்போக்கு"],
    "constipation": ["மலச்சிக்கல்"],
    "rash": ["தடிப்பு"],
    "itching": ["அரிப்பு"],
    "chills": ["குளிர்"],
    "breathlessness": ["மூச்சுத் திணறல்"],
    "insomnia": ["தூக்கமின்மை"],
    "cramps": ["பிடிப்புகள்"],
    "swelling": ["வீக்கம்"],
    "restlessness": ["அமைதியின்மை"],
    "sweating": ["வியர்வை"],
    "shivering": ["நடுங்குகிறது"],
  },
};
