import { StyleSheet } from 'react-native';
import { colors, spacing } from '../../theme';

export const styles = StyleSheet.create({
  headerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: spacing.md,
    position: 'relative',
    height: 56,
  },
  logoBadge: {
    width: 32,
    height: 32,
    borderRadius: 8,
    backgroundColor: colors.surfaceSoft,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: spacing.sm,
  },
  backButton: {
    position: 'absolute',
    left: 0,
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: colors.surface,
    shadowColor: colors.primaryAccent,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 12,
    elevation: 2,
    alignItems: 'center',
    justifyContent: 'center',
  },
  backArrowIcon: {
    width: 16,
    height: 16,
    justifyContent: 'center',
    alignItems: 'center',
    position: 'relative',
  },
  arrowStem: {
    position: 'absolute',
    width: 14,
    height: 2,
    backgroundColor: colors.textPrimary,
    borderRadius: 1,
    top: 7,
  },
  arrowHeadTop: {
    position: 'absolute',
    width: 8,
    height: 2,
    backgroundColor: colors.textPrimary,
    borderRadius: 1,
    left: 0,
    top: 4,
    transform: [{ rotate: '-45deg' }],
  },
  arrowHeadBottom: {
    position: 'absolute',
    width: 8,
    height: 2,
    backgroundColor: colors.textPrimary,
    borderRadius: 1,
    left: 0,
    top: 10,
    transform: [{ rotate: '45deg' }],
  },
  placeholderRight: {
    position: 'absolute',
    right: 0,
    width: 40,
    height: 40,
  },
});

export default styles;
